services:
  - type: web
    name: siyadah-whatsapp-platform
    env: node
    plan: standard
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CHROME_BIN
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: mongodb-cluster
          property: connectionString
    healthCheckPath: /api/health
    
databases:
  - name: mongodb-cluster
    databaseName: whatsapp_saas
    plan: standard